### ISSUE TITLE
Code Error in test.py

### ISSUE THREAD

**Issue by Kyu3224** [ziyanx02/multiagent-quadruped-environment#3]
I guess this is a trivial error but, on the line 2 of openrl_ws/test.py, there is no function "custom_cfg" in openrl_ws/utils.py but at mqe/envs/utils.py. So, doesn't it have to be changed as "from openrl_ws.utils import make_env, get_args, custom_cfg, MATWrapper" to "from openrl_ws.utils import make_env, get_args, MATWrapper" and "from mqe.env.utils import custom_cfg"? For me the latter case worked well.

**Comment by ziyanx02** [comment]
Thank you for raising the issue and providing a solution! This bug occurred while organizing the file directory. 

```
from openrl_ws.utils import make_env, get_args, custom_cfg, MATWrapper
```
should be replaced by
```
from openrl_ws.utils import make_env, get_args, MATWrapper
from mqe.env.utils import custom_cfg
```
