### ISSUE TITLE
parallel training

### ISSUE THREAD

**Issue by ghost** [ziyanx02/multiagent-quadruped-environment#5]
![image](https://github.com/user-attachments/assets/1817fce8-e45a-42a5-a742-a034f90b0a96)
how to do parallel training like the image?

**Comment by ziyanx02** [comment]
That is task "go1sheep-easy". You can try the task in `test.py` with `args.num_envs` changed and use your prefered MARL lib for training, or follow the README to install openrl and use `train.py` in openrl_ws for training.
